// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/resume/:id": {
    params: {
      "id": string;
    };
  };
  "/wipe": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/upload" | "/resume/:id" | "/wipe";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/upload";
  };
  "routes/resume.tsx": {
    id: "routes/resume";
    page: "/resume/:id";
  };
  "routes/wipe.tsx": {
    id: "routes/wipe";
    page: "/wipe";
  };
};